import { storage } from "@/server/core";
import { buildAdminReportPDF, type PDFReportInput, type PDFReportSection } from "@/server/pdf/reportBuilder";

/**
 * Generate a PDF report based on report type
 */
export async function generateReport(reportType: string): Promise<Uint8Array> {
  const now = new Date();
  const reportInput: PDFReportInput = {
    title: reportType,
    generatedAt: now.toLocaleString(),
    sections: [],
    footer: `Generated by ORBIT System on ${now.toLocaleDateString()}`,
  };

  try {
    switch (reportType) {
      case "Booking Summary":
        reportInput.sections = await generateBookingSummarySection();
        break;
      case "Equipment Usage":
        reportInput.sections = await generateEquipmentUsageSection();
        break;
      case "Facility Utilization":
        reportInput.sections = await generateFacilityUtilizationSection();
        break;
      case "User Activity":
        reportInput.sections = await generateUserActivitySection();
        break;
      case "System Alerts":
        reportInput.sections = await generateSystemAlertsSection();
        break;
      default:
        reportInput.sections = await generateBookingSummarySection();
    }

    return await buildAdminReportPDF(reportInput);
  } catch (error) {
    console.error(`[reportGenerator] Failed to generate ${reportType}:`, error);
    throw error;
  }
}

/**
 * Generate Booking Summary section
 */
async function generateBookingSummarySection(): Promise<PDFReportSection[]> {
  const bookings = await storage.getAllFacilityBookings();
  const facilities = await storage.getAllFacilities();
  const users = await storage.getAllUsers();

  const facilityMap = new Map(facilities.map((f: any) => [f.id, f.name]));
  const userMap = new Map(users.map((u: any) => [u.id, u.email]));

  // Stats
  const total = bookings.length;
  const approved = bookings.filter((b: any) => b.status === "approved").length;
  const pending = bookings.filter((b: any) => b.status === "pending").length;
  const cancelled = bookings.filter((b: any) => b.status === "cancelled").length;
  const denied = bookings.filter((b: any) => b.status === "denied").length;

  const statsSection: PDFReportSection = {
    title: "Booking Statistics",
    subtitle: "Overview of all facility bookings in the system",
    rows: [
      ["Total Bookings", total.toString()],
      ["Approved", approved.toString()],
      ["Pending", pending.toString()],
      ["Cancelled", cancelled.toString()],
      ["Denied", denied.toString()],
    ],
  };

  // Recent bookings (last 50)
  const recentBookings = bookings
    .sort((a: any, b: any) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, 50);

  const bookingsSection: PDFReportSection = {
    title: "Recent Bookings",
    subtitle: "Most recent 50 bookings",
    rows: [
      ["Facility", "User", "Start Time", "End Time", "Status"],
      ...recentBookings.map((b: any) => [
        facilityMap.get(b.facilityId) || "Unknown",
        userMap.get(b.userId) || "Unknown",
        new Date(b.startTime).toLocaleString(),
        new Date(b.endTime).toLocaleString(),
        b.status,
      ]),
    ],
  };

  return [statsSection, bookingsSection];
}

/**
 * Generate Equipment Usage section
 */
async function generateEquipmentUsageSection(): Promise<PDFReportSection[]> {
  const bookings = await storage.getAllFacilityBookings();
  
  const equipmentCounts = new Map<string, number>();
  
  for (const booking of bookings) {
    if (booking.equipment && typeof booking.equipment === 'object') {
      const equip = booking.equipment as any;
      for (const [key, items] of Object.entries(equip)) {
        if (Array.isArray(items)) {
          for (const item of items) {
            const name = item.name || item.equipmentName || key;
            equipmentCounts.set(name, (equipmentCounts.get(name) || 0) + 1);
          }
        }
      }
    }
  }

  const sorted = Array.from(equipmentCounts.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 50);

  return [{
    title: "Equipment Usage Statistics",
    subtitle: "Most frequently requested equipment items",
    rows: [
      ["Equipment Name", "Usage Count"],
      ...sorted.map(([name, count]) => [name, count.toString()]),
    ],
  }];
}

/**
 * Generate Facility Utilization section
 */
async function generateFacilityUtilizationSection(): Promise<PDFReportSection[]> {
  const bookings = await storage.getAllFacilityBookings();
  const facilities = await storage.getAllFacilities();

  const facilityStats = new Map<string, { name: string; approved: number; total: number }>();

  for (const facility of facilities) {
    facilityStats.set(String(facility.id), {
      name: facility.name,
      approved: 0,
      total: 0,
    });
  }

  for (const booking of bookings) {
    const stats = facilityStats.get(String(booking.facilityId));
    if (stats) {
      stats.total++;
      if (booking.status === "approved") {
        stats.approved++;
      }
    }
  }

  const sorted = Array.from(facilityStats.values())
    .sort((a, b) => b.total - a.total);

  return [{
    title: "Facility Utilization",
    subtitle: "Booking statistics by facility",
    rows: [
      ["Facility", "Total Bookings", "Approved Bookings", "Utilization %"],
      ...sorted.map((stat: any) => [
        stat.name,
        stat.total.toString(),
        stat.approved.toString(),
        stat.total > 0 ? ((stat.approved / stat.total) * 100).toFixed(1) + "%" : "0%",
      ]),
    ],
  }];
}

/**
 * Generate User Activity section
 */
async function generateUserActivitySection(): Promise<PDFReportSection[]> {
  const bookings = await storage.getAllFacilityBookings();
  const users = await storage.getAllUsers();

  const userStats = new Map<string, { email: string; bookings: number }>();

  for (const user of users) {
    userStats.set(user.id, { email: user.email, bookings: 0 });
  }

  for (const booking of bookings) {
    const stats = userStats.get(booking.userId);
    if (stats) {
      stats.bookings++;
    }
  }

  const sorted = Array.from(userStats.values())
    .filter((s: any) => s.bookings > 0)
    .sort((a: any, b: any) => b.bookings - a.bookings)
    .slice(0, 50);

  return [{
    title: "User Activity",
    subtitle: "Top 50 most active users by booking count",
    rows: [
      ["User Email", "Total Bookings"],
      ...sorted.map((stat: any) => [stat.email, stat.bookings.toString()]),
    ],
  }];
}

/**
 * Generate System Alerts section
 */
async function generateSystemAlertsSection(): Promise<PDFReportSection[]> {
  const alerts = await storage.getSystemAlerts();

  const recentAlerts = alerts
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, 100);

  const severityCounts = {
    low: alerts.filter(a => a.severity === "low").length,
    medium: alerts.filter(a => a.severity === "medium").length,
    high: alerts.filter(a => a.severity === "high").length,
  };

  const statsSection: PDFReportSection = {
    title: "Alert Statistics",
    rows: [
      ["Total Alerts", alerts.length.toString()],
      ["Low Severity", severityCounts.low.toString()],
      ["Medium Severity", severityCounts.medium.toString()],
      ["High Severity", severityCounts.high.toString()],
    ],
  };

  const alertsSection: PDFReportSection = {
    title: "Recent Alerts",
    subtitle: "Most recent 100 system alerts",
    rows: [
      ["Type", "Severity", "Title", "Created At"],
      ...recentAlerts.map((a: any) => [
        a.type,
        a.severity,
        a.title,
        new Date(a.createdAt).toLocaleString(),
      ]),
    ],
  };

  return [statsSection, alertsSection];
}
